name: Testing actions

on:
    push:
     branches:
      - 'main'
    pull_request:
     branches:
      - 'main'

jobs:
    test1:
     runs-on: ubuntu-latest

     steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: requirements
        run: pip install -r requirements.txt
      - name: unit tests
        run: python tests_training.py
      - name: boolean
        run: "False"