name: Testing actions

on:
    push:
     branches:
      - 'main'
    pull_request:
     branches:
      - 'main'

jobs:
    test1:
     runs-on: ubuntu-latest

     steps:
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.10' 
      - name: unit tests
        run: python tests_training.py