name: Testing actions

on:
   #execute action when a push is made on 'main' branch
    push:
     branches:
      - 'main'
   #execute action when a 'pull request' is made on 'main' branch
    pull_request:
     branches:
      - 'main'

jobs:
    test1:
      #set enviroment to run actions
     runs-on: ubuntu-latest

     steps:
      #action to check code
      - name: checkout code
        uses: actions/checkout@v3

      #set python enviroment for testing
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      #install pytest framework and run unit tests
      - name: unit tests
        run: |
         pip install pytest
         pytest tests_training.py